---
# The cloud_init_* variables are used by the cloudcodger.proxmox_client.cloud_init role
cloud_init_ansible_inventory_refresh: true
cloud_init_construct_hosts: [ gadget1, gadget2, gadget3 ]
cloud_init_disk_storage: local-lvm
cloud_init_image: ubuntu-24.04-server.qcow2
# cloud_init_network_gw: 192.168.6.1
# cloud_init_network_gw6: "2607:fa18:d7fe:ff00::1"
