---
ansible_python_interpreter: /usr/bin/python3
ansible_user: root

# Used by cloudcodger.proxmox_ve.authorized_keys
authorized_keys_allow:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwXgG2EeG5jv/2HmsxF/AjcG62p65hoIMtBTWP/VRaB Cloud-Codger
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOlL2ijDshLOTzn7wgk0fMLKmWgvVxNTD0OnDae5+Qfe sage@nomad.local
  - "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/showcase.pub') }}"

authorized_keys_deny:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPMFTr31EjjWadkvE/H9zJm0xklizbAOAMjtVVGctDXr retired@computer.local

# Used by cloudcodger.proxmox_ve.cluster
cluster_hosts_file_domain: "lab.{{ showcase_base_domain }}"
cluster_name: lab

# Used by cloudcodger.proxmox_ve.pve_exporter
pve_exporter_api_host: "{{ groups['proxmox_hosts'] | first }}"
pve_exporter_token_secret_prefix: lab-

# Used by cloudcodger.proxmox_ve.upload
upload_cloud_init_files:
  # - debian-12-genericcloud-amd64.qcow2
  # - debian-12-qemu-guest.qcow2
  - ubuntu-24.04-qemu-guest.qcow2
  - ubuntu-24.04-server.qcow2
# Alternatively, the commented out line will build the list of image files from the 'files' directory contents.
# upload_cloud_init_files: "{{ lookup('ansible.builtin.fileglob', 'files/*.qcow2', wantlist=True) | map('basename') }}"

upload_iso_images:
  - proxmox-ve_8.4-1.iso
# upload_iso_path: /mnt/pve/cephfs/template/iso
# upload_shared_iso_path: true
# Alternatively, the commented out line will build the list of image files from the 'files' directory contents.
# upload_iso_images: "{{ lookup('ansible.builtin.fileglob', 'files/*.iso', wantlist=True) | map('basename') }}"

upload_lxc_templates:
  - debian-12-standard_12.12-1_amd64.tar.zst
# Alternatively, the commented out line will build the list of image files from the 'files' directory contents.
# upload_lxc_templates: "{{ lookup('ansible.builtin.fileglob', 'files/*.zst', wantlist=True) | map('basename') }}"
